# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test, Build and Deliver

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test, Build and Deliver
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
      - name: Install
        run: npm ci
      - name: Test
        run: |
          npm run lint
          npm run format
          npm run test
          npm run coverage
      - name: Build
        run: npm run build
      - name: Deliver
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: sftp://home292045786.1and1-data.host
          ftp-username: u54145776-apps
          ftp-password: "mg3.cAwq8z3Er@@"
          known-hosts: "home292045786.1and1-data.host ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/tKA7T9UUfVZ4gSGezw3t98UQcWwtHqPildhNL7F4SKhhXJorT01hwqsTVPXz9Emr1IzS9iOvvynqh7N3xSs01qoucho8WeantCVI5H7Vwt00qS8z8BRiYk1WpyzJfUCNUUHSJhF5SJd03uWrP19AhGsqqj7/24IzGhqxN/FqHgHdBRkQB//XlHhw5e03DPkr5jQRlHjSb9lkWily0/meBTkd7lFRC2n0sT/KE4XbjpvQlc2IUIIeWHJfcsJgpaGcDFboN9oV//voE4A0pdAFwE4OByVDZa/ifgXRlT0k5vVS+EaxTtH8idiu6ZV/P7dLMDo7b76KTSxlSixn7hPh"
          local-dir: dist/
          dry-run: true
