# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test, Build and Deliver

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test, Build and Deliver
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
      - name: Install
        run: npm ci
      - name: Test
        run: |
          npm run lint
          npm run format
          npm run test
          npm run coverage
      - name: Build
        run: npm run build
      - name: Deliver
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: home292045786.1and1-data.host
          username: u54145776-apps
          password: mg3.cAwq8z3Er@@
          local-dir: dist/
          dry-run: true
